#! /bin/sh
############################################################
#
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝
#
#  Edited by Shishqa 
#
############################################################

export BSPWM_CONFIG="$HOME/.config/bspwm"

############################################################

bspc config window_gap              16

bspc config border_width            2
bspc config normal_border_color     "#A7A7A7"
bspc config focused_border_color    "#D9E5D6"

bspc config split_ratio             0.6180
bspc config automatic_scheme        longest_side
bspc config removal_adjustment      true
bspc config auto_cancel             true
bspc config initial_polarity        second_child

bspc config borderless_monocle      false
bspc config gapless_monocle         false

bspc config focus_follows_pointer   true
bspc config history_aware_focus     true
bspc config focus_by_distance       true

############################################################

bspc monitor --reset-desktops TTY WEB CHAT DEV MED PROP

bspc rule --add Firefox                   desktop='WEB'       follow=on
###
bspc rule --add TelegramDesktop           desktop='CHAT'      follow=on
###
bspc rule --add jetbrains-clion           desktop='DEV'       follow=on
bspc rule --add jetbrains-pycharm         desktop='DEV'       follow=on
bspc rule --add edb                       desktop='DEV'       follow=on
###
bspc rule --add libreoffice-startcenter   desktop='MED'       follow=on  
###
bspc rule --add Gimp                      desktop='MED'       follow=on
bspc rule --add Inkscape                  desktop='MED'       follow=on
bspc rule --add Dia                       desktop='MED'       follow=on state=floating
###
bspc rule --add Nitrogen                  desktop='PROP'      follow=on
bspc rule --add Lxappearance              desktop='PROP'      follow=on
###
bspc rule --add Pick-colour-picker        state=floating sticky=on
bspc rule --add vlc                       state=floating 
bspc rule --add feh                       state=floating 
bspc rule --add URxvt:calendar            state=floating
bspc rule --add URxvt:htop                state=floating
bspc rule --add URxvt:ncmpcpp             state=floating
bspc rule --add URxvt:update              state=floating

sxhkd &
"$BSPWM_CONFIG/autostart" &

############################################################
#
#  ███████╗ ██████╗ ███████╗
#  ██╔════╝██╔═══██╗██╔════╝
#  █████╗  ██║   ██║█████╗
#  ██╔══╝  ██║   ██║██╔══╝
#  ███████╗╚██████╔╝██║
#  ╚══════╝ ╚═════╝ ╚═╝
#
############################################################
