#!/usr/bin/env bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

CONFIG=$HOME/.config/polybar/bars.ini

# Launch bar
polybar --config=$CONFIG info  -rq &
polybar --config=$CONFIG wm    -rq &
polybar --config=$CONFIG cal   -rq &
