#!/usr/bin/env bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

CONFIG=$HOME/.config/polybar/

# Launch bar
polybar --config=$CONFIG/bar-top.ini top &
polybar --config=$CONFIG/bar-bottom.ini bottom &
