#!/bin/sh

# options to be displayed
option0="lock"
option1="reload"
option2="reboot"
option3="shutdown"

# options passed into variable
options="$option0\n$option1\n$option2\n$option3"

chosen="$(echo -e "$options" | rofi -lines 4 -dmenu -p "power")"
case $chosen in
    $option0)
        sleep 0.5
        lock;;
    $option1)
        bspc quit;;
    $option2)
        systemctl reboot;;
	$option3)
        systemctl poweroff;;
esac
